//IEFDesktopConfigurations.java

import matrix.db.Context;

public class IEFDesktopConfigurations_mxJPO
{
	public String typeNavigationMappings = "";
	public String typeUnSupportedExt = "";

	public IEFDesktopConfigurations_mxJPO (Context context, String[] args) throws Exception
    {
		init();
	}

	private void init()
	{
		typeNavigationMappings = "type_ProjectSpace|@command_MsoiPMCFolders\ntype_InboxTask|@command_MSFInboxTaskAttachment\ntype_Project|relationship_VaultedDocuments@command_IEFDesktopTMCFolder\ntype_Library|relationship_ReferenceDocument,relationship_Subclass@command_IEFDesktopObjectSummary\ntype_PartLibrary|relationship_ReferenceDocument,relationship_Subclass@command_IEFDesktopObjectSummary\ntype_GeneralLibrary|relationship_ReferenceDocument,relationship_Subclass@command_IEFDesktopObjectSummary\ntype_DocumentFamily|relationship_ReferenceDocument,relationship_ClassifiedItem,relationship_Subclass@command_IEFDesktopObjectSummary\ntype_GeneralClass|relationship_ReferenceDocument,relationship_ClassifiedItem,relationship_Subclass@command_IEFDesktopObjectSummary\ntype_LogicalFeature|relationship_ReferenceDocument,relationship_FeaturesSpecification,relationship_LogicalFeatures,relationship_FeatureTestCase,relationship_FeatureUseCase,relationship_RequirementSatisfiedBy,relationship_ManufacturingFeatures@command_MsoiDocumentSummary\ntype_ManufacturingFeature|relationship_ReferenceDocument,relationship_FeaturesSpecification,relationship_LogicalFeatures,relationship_ManufacturingFeatures,relationship_FeatureTestCase,relationship_FeatureUseCase,relationship_RequirementSatisfiedBy@command_MsoiDocumentSummary\ntype_ConfigurationFeature|relationship_ReferenceDocument,relationship_FeaturesSpecification,relationship_ConfigurationFeatures,relationship_FeatureTestCase,relationship_FeatureUseCase,relationship_RequirementSatisfiedBy@command_MsoiDocumentSummary\ntype_Requirement|relationship_RequirementBreakdown,relationship_RequirementUseCase,relationship_RequirementValidation,relationship_ReferenceDocument@command_MsoiDocumentSummary\ntype_TestCase|relationship_SubTestCase,relationship_ReferenceDocument@command_MsoiDocumentSummary\ntype_UseCase|relationship_SubUseCase,relationship_ReferenceDocument@command_MsoiDocumentSummary\ntype_Task|relationship_Subtask,relationship_TaskDeliverable@command_IEFDesktopObjectSummary\ntype_Part|menu_MsoiPart\ntype_Products|relationship_ReferenceDocument,relationship_ProductSpecification,relationship_ProductBuild,relationship_ConfigurationFeatures,relationship_LogicalFeatures,relationship_ManufacturingFeatures,relationship_ProductRequirement,relationship_ProductConfiguration,relationship_AssociatedManufacturingPlans,relationship_RoadmapTask,relationship_ProductVersion@command_MsoiDocumentSummary\ntype_Builds|menu_MsoiBuilds\ntype_ProjectVault|relationship_VaultedDocuments,relationship_VaultedDocumentsRev2,relationship_SubVaults@command_IEFDesktopObjectSummary\ntype_PartFamily|relationship_ClassifiedItem,relationship_PartFamilyReferenceDocument,relationship_Subclass@command_MsoiDocumentSummary\ntype_ProductConfiguration|relationship_ProductConfigurationBuild@command_IEFDesktopObjectSummary\ntype_ManufacturingPlan|relationship_ReferenceDocument@command_IEFDesktopObjectSummary\ntype_Meeting|relationship_MeetingAttachments@command_IEFDesktopObjectSummary\ntype_HardwareBuild|relationship_ReferenceDocument@command_IEFDesktopObjectSummary\ntype_SoftwareBuild|relationship_ReferenceDocument@command_IEFDesktopObjectSummary";
		typeUnSupportedExt	       ="ipt,iam,idw,ipn,asm,cfg,par,dft,psm,pwd,prt,asm,drw,dgm,frm,lay,mfg,SLDPRT,SLDASM,SLDDRW,prt,dgn,dwg,CATPart,CATProduct,CADDrawing";
	}

	public String getTypeNavigationMappings()
	{
		return typeNavigationMappings;
	}

	public String getDefaultActionMenu(Context context) throws Exception
	{
		String defaultActionsMenu = "IEFDesktopActionsMenu";
		
		return defaultActionsMenu;
	}

	public String  getTypeUnSupportedExt( Context context,String[] args)
	{
		return typeUnSupportedExt;
	}


}
